#!/bin/bash
set -e

# first we generate the shibboleth2.xml file based on environment variables passed in
# sp_idp=https://imp.bu.edu/idp/shibboleth
# sp_sp=http://imp.bu.edu:8000/shibboleth
# sp_skip_update=yes
#
if [ "x$sp_skip_update" = "x" ]; then
  # set defaults
  [ "x$sp_idp" = "x" ] && sp_idp="https://imp.bu.edu/idp/shibboleth"
  [ "x$sp_sp" = "x" ] && sp_sp="http://imp.bu.edu:8000/shibboleth"

  sed "s#SP_ENTITY_ID#$sp_sp#" </etc/shibboleth/shibboleth2-template.xml \
    | sed "s#SHIB_SP_KEY#$SHIB_SP_KEY#" \
    | sed "s#SHIB_SP_CERT#$SHIB_SP_CERT#" \
    | sed "s#IDP_ENTITY_ID#$sp_idp#" >/etc/shibboleth/shibboleth2.xml

  # get the idp-metadata.xml automatically from the sp_idp location
  wget --no-check-certificate "$sp_idp" -P /tmp
  if [ -r "/tmp/shibboleth" ]; then
    mv /tmp/shibboleth /etc/shibboleth/idp-metadata.xml
  fi 
fi

/etc/shibboleth/shibd-redhat start

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid
exec httpd -DFOREGROUND
