#!/bin/bash
set -e

for f in /entrypoints/entrypoints.d/*; do
    echo "Launching $f"
    bash "$f" -H
done


# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid
exec httpd -DFOREGROUND
